global_defs {
    router_id LB2
}

vrrp_instance VI_EXT {
    state BACKUP
    interface enp0s8
    virtual_router_id 10
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass tp-ha
    }
    unicast_src_ip 10.99.99.12
    unicast_peer {
        10.99.99.11
    }
    virtual_ipaddress {
        192.168.10.100/24 dev enp0s8
    }
}

vrrp_instance VI_INT {
    state BACKUP
    interface enp0s9
    virtual_router_id 20
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass tp-ha
    }
    unicast_src_ip 10.99.99.12
    unicast_peer {
        10.99.99.11
    }
    virtual_ipaddress {
        192.168.20.100/24 dev enp0s9
    }
}
