global_defs {
    router_id LB1
}

vrrp_instance VI_EXT {
    state MASTER
    interface enp0s8
    virtual_router_id 10
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass tp-ha
    }
    unicast_src_ip 10.99.99.11
    unicast_peer {
        10.99.99.12
    }
    virtual_ipaddress {
        192.168.10.100/24 dev enp0s8
    }
}

vrrp_instance VI_INT {
    state MASTER
    interface enp0s9
    virtual_router_id 20
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass tp-ha
    }
    unicast_src_ip 10.99.99.11
    unicast_peer {
        10.99.99.12
    }
    virtual_ipaddress {
        192.168.20.100/24 dev enp0s9
    }
}
