global_defs {
    router_id LB1
    enable_script_security
    script_user root
    script_user root
}

vrrp_script chk_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval 2
    weight -30
    fall 2
    rise 2
}

vrrp_sync_group VG_PORTAIL {
    group {
        VI_LAN
        VI_DMZ
    }
    notify /etc/keepalived/notify.sh
}

vrrp_instance VI_LAN {
    state MASTER
    interface enp0s8
    virtual_router_id 10
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass __VRRP_PASS_DANS_GESTIONNAIRE__
    }
    virtual_ipaddress {
        192.168.10.100/24
    }
    track_script {
        chk_haproxy
    }
}

vrrp_instance VI_DMZ {
    state MASTER
    interface enp0s9
    virtual_router_id 20
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass __VRRP_PASS_DANS_GESTIONNAIRE__
    }
    virtual_ipaddress {
        192.168.20.100/24
    }
    track_script {
        chk_haproxy
    }
}
