#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept
        ct state established,related accept
        ip protocol icmp accept
        iifname "enp0s3" tcp dport 22 accept
        iifname "enp0s10" tcp dport 22 accept
        iifname "enp0s8" tcp dport { 80, 443 } accept
        iifname "enp0s10" tcp dport 8404 accept
        iifname "enp0s8" ip protocol 112 accept
        iifname "enp0s9" ip protocol 112 accept
        log prefix "nft-DROP-lb1: " drop
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
        iifname "enp0s9" oifname "enp0s3" accept
        iifname "enp0s3" oifname "enp0s9" ct state established,related accept
        log prefix "nft-DROP-forward-lb1: " drop
    }
    chain output { type filter hook output priority 0; policy accept; }
}
